# Generated by Django 5.0.1 on 2024-02-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(default='', max_length=255)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('is_default', models.BooleanField(default=True)),
                ('sprite_url', models.URLField(default='')),
            ],
        ),
    ]
